### PR TITLE
typo

### PR DESCRIPTION
**Pull request by xalexec**
typo comma

### CODE REVIEW

**Comment by xalexec** [comment]
can add me to  https://vuefe.cn/about/ ?

this is my pr
https://github.com/vuefe/vuefe.github.io/pull/300
https://github.com/vuefe/vuefe.github.io/pull/292

**Comment by 70data** [comment]
Will add unified later

**Comment by xalexec** [comment]
line 79 has two comma，😭

**Comment by dingyiming** [comment]
@xalexec 已添加到贡献者名单

**Pull request closed without merging**
